### PR TITLE
Merge josh/build into develop

### PR DESCRIPTION
**Pull request by joshstricklin**
Add HTML Minification, image optimization to build process.

### CODE REVIEW

**Comment by RamZallan** [comment]
:zap:

**Comment by vishalarora** [comment]
@Waveharp, before merging this into `develop`, please review #3 and provide feedback and/or merge that.

**Comment by vishalarora** [comment]
Once #3 is merged in, this looks good to me.

👍

**Comment by vishalarora** [comment]
@Waveharp:  re 71b0c2080d83c826d4b9d2c80468d2ae62904f4d, you shouldn't need to merge `develop` into this branch.  Rebasing is a much more elegant solution to get your feature branch up-to-date.  Remind me to give you a primer if you need one. :)

**Pull request merged**
