### PR TITLE
Add Hound & LGTM 

### PR DESCRIPTION
**Pull request by vishalarora**

### CODE REVIEW

**Comment by vishalarora** [comment]
This is cheating a little but I'm testing to see if it works.

👍

**Comment by joshstricklin** [comment]
So all I have to say is LGTM and it merges? Looks good to me!

**Comment by vishalarora** [comment]
⚡ 
👍 
:shipit:

**Comment by RamZallan** [comment]
:zap:

**Comment by vishalarora** [comment]
Testing this again.  I'm guessing that my customizations won't work until this PR is merged.  LGTM 👍 :shipit:

**Comment by vishalarora** [comment]
looks good to me

**Pull request merged**
